### ISSUE TITLE
Bug in BestFragmentsInField

### ISSUE THREAD

**Issue by blackreign** [blevesearch/bleve#219] opened 2015-07-21 19:07 UTC
Searching for "en" gives this stacktrace. Other searches appear to be fine

<b>runtime error: slice bounds out of range</b>

c:/go/src/runtime/panic.go:387 (0x41d3af)
c:/go/src/runtime/panic.go:18 (0x41c525)
E:/Project/GO/src/github.com/blevesearch/bleve/search/highlight/fragmenters/simple/fragmenter_simple.go:57 (0x86c9e6)
	(*Fragmenter).Fragment: r, size := utf8.DecodeLastRune(orig[0:start])
E:/Project/GO/src/github.com/blevesearch/bleve/search/highlight/highlighters/simple/highlighter_simple.go:84 (0x86d916)
	(*Highlighter).BestFragmentsInField: fragments := s.fragmenter.Fragment(fieldData, orderedTermLocations)
E:/Project/GO/src/github.com/blevesearch/bleve/index_impl.go:447 (0x6b8e74)
	(*indexImpl).Search: highlighter.BestFragmentsInField(hit, doc, hf, 1)
E:/Project/GO/src/Project2015/forum/controllers/search_page.go:88 (0x69430b)
	searchInIndex: searchResults, err := index.Search(req)
E:/Project/GO/src/Project2015/forum/controllers/search_page.go:261 (0x696f7e)
	searchForumgroups: matches, err := searchInIndex(managers.Forumgroup_index, data)
E:/Project/GO/src/Project2015/forum/controllers/search_page.go:195 (0x69617b)
	searchForum: forumgroup_matches, err := searchForumgroups(data)
E:/Project/GO/src/Project2015/forum/controllers/search_page.go:30 (0x69350a)
	Search_page: case "forum":				{ matches, err = searchForum(data) }
E:/Project/GO/src/Project2015/page_generators/general_layout_wrapper.go:27 (0x45df00)
	(*General_layout_wrapper).ServeHTTP: redirect_string, status_code := gen.forum_func(forum_content, w, r)
E:/Project/GO/src/Project2015/forum/gobb/gobb.go:14 (0x4bf2d6)
	*General_layout_wrapper.ServeHTTP.fm: return page_generators.NewGeneralLayoutWrapper(p_func).ServeHTTP
c:/go/src/net/http/server.go:1265 (0x49b2a8)
E:/Project/GO/src/github.com/gorilla/mux/mux.go:98 (0x66507e)
	(*Router).ServeHTTP: handler.ServeHTTP(w, req)
E:/Project/GO/src/Project2015/Project2015.go:40 (0x40aa40)
	func.002: (*MuxForum).ServeHTTP(w,r)
c:/go/src/runtime/asm_amd64.s:402 (0x430bec)
c:/go/src/reflect/value.go:419 (0x4fe22c)
c:/go/src/reflect/value.go:296 (0x4fd023)
e:/Project/gocode/src/github.com/codegangsta/inject/inject.go:102 (0x50fe4e)
:30 (0x45765d)
E:/Project/GO/src/github.com/go-martini/martini/router.go:371 (0x4535ff)
	(*routeContext).run: vals, err := r.Invoke(handler)
E:/Project/GO/src/github.com/go-martini/martini/router.go:249 (0x451e6d)
	(*route).Handle: context.run()
E:/Project/GO/src/github.com/go-martini/martini/router.go:120 (0x4501a7)
	(*router).Handle: route.Handle(context, res)
E:/Project/GO/src/github.com/go-martini/martini/martini.go:119 (0x454752)
	Router.Handle.fm: m.Action(r.Handle)
c:/go/src/runtime/asm_amd64.s:403 (0x430c5c)
c:/go/src/reflect/value.go:419 (0x4fe22c)
c:/go/src/reflect/value.go:296 (0x4fd023)
e:/Project/gocode/src/github.com/codegangsta/inject/inject.go:102 (0x50fe4e)
E:/Project/GO/src/github.com/go-martini/martini/martini.go:173 (0x44cf58)
	(*context).run: _, err := c.Invoke(c.handler())
E:/Project/GO/src/github.com/go-martini/martini/martini.go:164 (0x44cddb)
	(*context).Next: c.run()
E:/Project/GO/src/github.com/go-martini/martini/recovery.go:142 (0x455018)
	func.004: c.Next()
c:/go/src/runtime/asm_amd64.s:402 (0x430bec)
c:/go/src/reflect/value.go:419 (0x4fe22c)
c:/go/src/reflect/value.go:296 (0x4fd023)
e:/Project/gocode/src/github.com/codegangsta/inject/inject.go:102 (0x50fe4e)
E:/Project/GO/src/github.com/go-martini/martini/martini.go:173 (0x44cf58)
	(*context).run: _, err := c.Invoke(c.handler())
E:/Project/GO/src/github.com/go-martini/martini/martini.go:164 (0x44cddb)
	(*context).Next: c.run()
E:/Project/GO/src/github.com/go-martini/martini/logger.go:25 (0x4543b2)
	func.001: c.Next()
c:/go/src/runtime/asm_amd64.s:403 (0x430c5c)
c:/go/src/reflect/value.go:419 (0x4fe22c)
c:/go/src/reflect/value.go:296 (0x4fd023)
e:/Project/gocode/src/github.com/codegangsta/inject/inject.go:102 (0x50fe4e)
E:/Project/GO/src/github.com/go-martini/martini/martini.go:173 (0x44cf58)
	(*context).run: _, err := c.Invoke(c.handler())
E:/Project/GO/src/github.com/go-martini/martini/martini.go:69 (0x44bab5)
	(*Martini).ServeHTTP: m.createContext(res, req).run()
c:/go/src/net/http/server.go:1703 (0x49d3d1)
c:/go/src/net/http/server.go:1204 (0x49adde)
c:/go/src/runtime/asm_amd64.s:2232 (0x432e71)

**Comment by mschoch** [comment] 2015-07-21 19:12
Can you provide the original source for this document?

**Comment by blackreign** [comment] 2015-07-21 19:17
Greetings and thanks for your reply.

The error happens when searching using the index that indexes the following struct

type Forumgroup struct {
	Id                 int            `db:"id"`
	Name               string           `db:"name"`
	Forum_category_id  int            `db:"forum_category_id"`
	Ordering           int            `db:"ordering"`
	ForumCategory      *ForumCategory   `db:"-"`
	Forums             []*Forum         `db:"-"`
}

The function below does the searching. From the Goclipse output, I conclude that the execution stops before the fmt statement.

func searchInIndex(index bleve.Index, data *SearchPageData) ([]*Match, error) {
	query := bleve.NewQueryStringQuery(data.Phrase)
	fmt.Println(data.Terms)
    req := bleve.NewSearchRequest(query)
	req.Highlight = bleve.NewHighlight()
    searchResults, err := index.Search(req)
    fmt.Println(searchResults)
    if err != nil {
        fmt.Println(err)
        return nil, err
    }
    var result []*Match
    for _, hit := range searchResults.Hits {
        m := Match{Id:hit.ID}
        m.Field, m.Highlight = getFirstFragment(hit) 
        result = append(result, &m)
   	}
    return result, nil
}

**Comment by mschoch** [comment] 2015-07-21 19:21
Thanks that helps some, but the formatting is crashing because of something unexpected/unhandled in the data.  It would help a lot if you could isolate which particular piece of data caused the problem.

For example, searching and highilighting "end" works here:

http://www.blevesearch.com/search/?q=en

So, it is not the case that highlighting "en" always fails, instead it something about trying to highlight "en" within a particular piece of your data.  If you can help provide that, it will be easier to debug.

**Comment by blackreign** [comment] 2015-07-21 19:28
The thing is, that the structs are indexed when the server starts, and joins may or may not be set at that time. It is therefore difficult to isolate the exact document that illustrates the problem.

The structs are initalised from a database table that holds 47 records that contain where each field is set.
Deleting the index and reindexing did not solve the issue. I could try to isolate the specific document by incrementally indexing the structs/documents, until the problem occurs.

**Comment by mschoch** [comment] 2015-07-21 19:29
Yes that would help a lot.  Is it possible to do that?

**Comment by blackreign** [comment] 2015-07-21 19:41
I have isolated a or the struct causing the problem.

&forum_datamodel.Forumgroup{Id:4, Name:"Algemene duurzame onderwerpen", Forum_category_id:4, Ordering:1, ForumCategory:(*forum_datamodel.ForumCategory)(nil), Forums:[]*forum_datamodel.Forum{(*forum_datamodel.Forum)(0xc082274cf0), (*forum_datamodel.Forum)(0xc082274d80), (*forum_datamodel.Forum)(0xc082274f30), (*forum_datamodel.Forum)(0xc082275050), (*forum_datamodel.Forum)(0xc082275200), (*forum_datamodel.Forum)(0xc082275290), (*forum_datamodel.Forum)(0xc082275320), (*forum_datamodel.Forum)(0xc0822753b0)}}

**Comment by blackreign** [comment] 2015-07-21 19:42
```
func createForumgroupIndex(index_path string) bleve.Index {
  	txt_field_mapping := bleve.NewTextFieldMapping()
  	txt_field_mapping.IncludeInAll = false
  	txt_field_mapping.Analyzer = "en"
  	item_mapping := bleve.NewDocumentMapping()
  	item_mapping.AddFieldMappingsAt("Name", txt_field_mapping)
	index_mapping := bleve.NewIndexMapping()
	index_mapping.AddDocumentMapping("forumgroup", item_mapping)
	index_mapping.DefaultAnalyzer = "en"
    index, err := bleve.New(index_path, index_mapping)
    if err != nil {
	    log.Fatal(err)
    }
    return index
}
```

**Comment by mschoch** [comment] 2015-07-21 19:45
Thanks this should be enough info.  I'll try to create a test case reproducing the problem within 24 hours.

**Comment by blackreign** [comment] 2015-07-21 19:48
Awesome!

**Comment by mschoch** [comment] 2015-07-22 13:34
OK, so far I'm still unsuccessful at the trying to reproduce the problem.  I had to make a few modifications as it turns out some things were still missing.

You can find the code I'm running here:

https://gist.github.com/mschoch/8f722ecf14e9ff63e167

Things missing:

1.  Forum structure definition
2.  Forum values in the problematic document "4" (they are just listed as pointers above)
3.  ForumCategory structure (probably not important since its nil in the problematic document
4.  SearchPageData - unclear how Phrase and Terms relate, Phrase is used in search, but Terms is printed out
5.  getFirstFragment() function definition - i created placeholder, because it seems like the crash you are seeing is before this gets called

Right now when I run the program I get:

```
$ ./bleve-test
Forum groep 4
&main.Forumgroup{Id:4, Name:"Algemene duurzame onderwerpen", Forum_category_id:4, Ordering:1, ForumCategory:(*main.ForumCategory)(nil), Forums:[]*main.Forum{}}
[en]
No matches
2015/07/22 09:29:03 Matches: []
```

Can you help provide the information above and/or see if you can modify the test program I started to make it reproduce the behavior you're seeing?

**Comment by blackreign** [comment] 2015-07-22 14:07
1. Forum structure
```
type Forum struct {
	Id            	int       						`db:"id"`
	Title         	string     						`db:"title"`
	Description		string							`db:"description"`
	Order         	int       						`db:"ordering"`
	Forum_group_id	int      						`db:"forum_group_id"`
	Post_count    	int	  							`db:"post_count"`
	Topic_count   	int       						`db:"topic_count"`
	Last_post_on   	pq.NullTime						`db:"last_post_on"`
	Forumgroup     	*Forumgroup						`db:"-"`
	Topics			[]*Topic						`db:"-"`
	Articlegroup	*article_datamodel.Articlegroup	`db:"-"`
}
```

2. Forum data
```
&forum_datamodel.Forumgroup{Id:4, Name:"Algemene duurzame onderwerpen", Forum_category_id:4, Ordering:1, ForumCategory:(*forum_datamodel.ForumCategory)(0xc08228f4a0), Forums:[]*forum_datamodel.Forum{(*forum_datamodel.Forum)(0xc082270900), (*forum_datamodel.Forum)(0xc082270990), (*forum_datamodel.Forum)(0xc082270b40), (*forum_datamodel.Forum)(0xc082270c60), (*forum_datamodel.Forum)(0xc082270e10), (*forum_datamodel.Forum)(0xc082270ea0), (*forum_datamodel.Forum)(0xc082270f30), (*forum_datamodel.Forum)(0xc082270fc0)}}
&forum_datamodel.Forum{Id:18, Title:"Actualiteit, Sport & Politiek", Description:".", Order:1, Forum_group_id:4, Post_count:0, Topic_count:0, Last_post_on:pq.NullTime{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}, Valid:false}, Forumgroup:(*forum_datamodel.Forumgroup)(nil), Topics:[]*forum_datamodel.Topic(nil), Articlegroup:(*article_datamodel.Articlegroup)(nil)}
&forum_datamodel.Forum{Id:19, Title:"Film, TV & Muziek", Description:".", Order:1, Forum_group_id:4, Post_count:0, Topic_count:0, Last_post_on:pq.NullTime{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}, Valid:false}, Forumgroup:(*forum_datamodel.Forumgroup)(nil), Topics:[]*forum_datamodel.Topic(nil), Articlegroup:(*article_datamodel.Articlegroup)(nil)}
&forum_datamodel.Forum{Id:20, Title:"Spelletjes", Description:".", Order:1, Forum_group_id:4, Post_count:0, Topic_count:0, Last_post_on:pq.NullTime{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}, Valid:false}, Forumgroup:(*forum_datamodel.Forumgroup)(nil), Topics:[]*forum_datamodel.Topic(nil), Articlegroup:(*article_datamodel.Articlegroup)(nil)}
&forum_datamodel.Forum{Id:21, Title:"Werk en Inkomen", Description:".", Order:1, Forum_group_id:4, Post_count:0, Topic_count:0, Last_post_on:pq.NullTime{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}, Valid:false}, Forumgroup:(*forum_datamodel.Forumgroup)(nil), Topics:[]*forum_datamodel.Topic(nil), Articlegroup:(*article_datamodel.Articlegroup)(nil)}
&forum_datamodel.Forum{Id:22, Title:"Wetenschap & Levensbeschouwing", Description:".", Order:1, Forum_group_id:4, Post_count:0, Topic_count:0, Last_post_on:pq.NullTime{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}, Valid:false}, Forumgroup:(*forum_datamodel.Forumgroup)(nil), Topics:[]*forum_datamodel.Topic(nil), Articlegroup:(*article_datamodel.Articlegroup)(nil)}
&forum_datamodel.Forum{Id:23, Title:"Vervoer", Description:".", Order:1, Forum_group_id:4, Post_count:0, Topic_count:0, Last_post_on:pq.NullTime{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}, Valid:false}, Forumgroup:(*forum_datamodel.Forumgroup)(nil), Topics:[]*forum_datamodel.Topic(nil), Articlegroup:(*article_datamodel.Articlegroup)(nil)}
&forum_datamodel.Forum{Id:24, Title:"Shopping Forum", Description:".", Order:1, Forum_group_id:4, Post_count:0, Topic_count:0, Last_post_on:pq.NullTime{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}, Valid:false}, Forumgroup:(*forum_datamodel.Forumgroup)(nil), Topics:[]*forum_datamodel.Topic(nil), Articlegroup:(*article_datamodel.Articlegroup)(nil)}
&forum_datamodel.Forum{Id:25, Title:"Aanbiedingen en Kortingscodes", Description:".", Order:1, Forum_group_id:4, Post_count:0, Topic_count:0, Last_post_on:pq.NullTime{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}, Valid:false}, Forumgroup:(*forum_datamodel.Forumgroup)(nil), Topics:[]*forum_datamodel.Topic(nil), Articlegroup:(*article_datamodel.Articlegroup)(nil)}
```

3. ForumCategory structure
```
type ForumCategory struct {
	Id              int         `db:"id"`
	Name            string        `db:"name"`
	Forumgroups     []*Forumgroup `db:"-"`
}
```

4. Phrase is just "en"
```
type SearchPageData struct {
    Search_type				string
    Phrase					string
    Terms					[]string
    Matches					[]*Match
    Page					int
    Page_count				int
    Page_count_minus_one	int
    Page_size				int
    Previous_page			int
    Next_page				int
    Hits					int
    Errors					[]string
	Functions				map[string]interface{}
}
```

5. getFirstFragment()
```
func getFirstFragment(hit *search.DocumentMatch) (string, string) {
	for fragmentField, fragments := range hit.Fragments {
	    for _, fragment := range fragments {
	        return fragmentField, fragment
	    }
	}
	return "",""
}
```

**Comment by blackreign** [comment] 2015-07-22 14:23
Just a hunch, but maybe the problem lies within the pg.NullTime data

**Comment by blackreign** [comment] 2015-07-22 14:34
Got the problem reproduced!

```
package main

import (
	"fmt"
	"github.com/blevesearch/bleve"
	"github.com/blevesearch/bleve/search"
	"log"
	"os"
	"strconv"
	"github.com/lib/pq"
	"time"
	
)

type ForumCategory struct {
	Id              int         `db:"id"`
	Name            string        `db:"name"`
	Forumgroups     []*Forumgroup `db:"-"`
}

type Forum struct {
	Id            	int       						`db:"id"`
	Title         	string     						`db:"title"`
	Description		string							`db:"description"`
	Order         	int       						`db:"ordering"`
	Forum_group_id	int      						`db:"forum_group_id"`
	Post_count    	int	  							`db:"post_count"`
	Topic_count   	int       						`db:"topic_count"`
	Last_post_on   	pq.NullTime						`db:"last_post_on"`
}

type Forumgroup struct {
	Id                int            `db:"id"`
	Name              string         `db:"name"`
	Forum_category_id int            `db:"forum_category_id"`
	Ordering          int            `db:"ordering"`
	ForumCategory     *ForumCategory `db:"-"`
	Forums            []*Forum       `db:"-"`
}

type SearchPageData struct {
	Phrase string
	Terms  []string
}

type Match struct {
	Id        string
	Field     string
	Highlight string
}

func createForumgroupIndex(index_path string) bleve.Index {
	txt_field_mapping := bleve.NewTextFieldMapping()
	txt_field_mapping.IncludeInAll = false
	txt_field_mapping.Analyzer = "en"
	item_mapping := bleve.NewDocumentMapping()
	item_mapping.AddFieldMappingsAt("Name", txt_field_mapping)
	index_mapping := bleve.NewIndexMapping()
	index_mapping.AddDocumentMapping("forumgroup", item_mapping)
	index_mapping.DefaultAnalyzer = "en"
	index, err := bleve.New(index_path, index_mapping)
	if err != nil {
		log.Fatal(err)
	}
	return index
}

func indexForumgroups(index bleve.Index, items []*Forumgroup) error {
	var err error
	for i := 0; i < len(items); i++ {
		fmt.Printf("Forum groep %v\n", items[i].Id)
		fmt.Printf("%#v\n", items[i])
		err = index.Index(strconv.Itoa(items[i].Id), items[i])
		if err != nil {
			return err
		}
	}
	return nil
}

func searchInIndex(index bleve.Index, data *SearchPageData) ([]*Match, error) {
	query := bleve.NewQueryStringQuery(data.Phrase)
	fmt.Println(data.Terms)
	req := bleve.NewSearchRequest(query)
	req.Highlight = bleve.NewHighlight()
	searchResults, err := index.Search(req)
	fmt.Println(searchResults)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	var result []*Match
	for _, hit := range searchResults.Hits {
		m := Match{Id: hit.ID}
		m.Field, m.Highlight = getFirstFragment(hit)
		result = append(result, &m)
	}
	return result, nil
}

func getFirstFragment(hit *search.DocumentMatch) (string, string) {
	return "", ""
}

func MakeBadForums() []*Forum {
    var result []*Forum
	result = append(result, &Forum{Id:18, Title:"Actualiteit, Sport & Politiek", Description:".", Order:1, Forum_group_id:4, Post_count:0, Topic_count:0, Last_post_on:pq.NullTime{Time:time.Time{}, Valid:false}})
	result = append(result, &Forum{Id:19, Title:"Film, TV & Muziek", Description:".", Order:1, Forum_group_id:4, Post_count:0, Topic_count:0, Last_post_on:pq.NullTime{Time:time.Time{}, Valid:false}})
	result = append(result, &Forum{Id:20, Title:"Spelletjes", Description:".", Order:1, Forum_group_id:4, Post_count:0, Topic_count:0, Last_post_on:pq.NullTime{Time:time.Time{}, Valid:false}})
	result = append(result, &Forum{Id:21, Title:"Werk en Inkomen", Description:".", Order:1, Forum_group_id:4, Post_count:0, Topic_count:0, Last_post_on:pq.NullTime{Time:time.Time{}, Valid:false}})
	result = append(result, &Forum{Id:22, Title:"Wetenschap & Levensbeschouwing", Description:".", Order:1, Forum_group_id:4, Post_count:0, Topic_count:0, Last_post_on:pq.NullTime{Time:time.Time{}, Valid:false}})
	result = append(result, &Forum{Id:23, Title:"Vervoer", Description:".", Order:1, Forum_group_id:4, Post_count:0, Topic_count:0, Last_post_on:pq.NullTime{Time:time.Time{}, Valid:false}})
	result = append(result, &Forum{Id:24, Title:"Shopping Forum", Description:".", Order:1, Forum_group_id:4, Post_count:0, Topic_count:0, Last_post_on:pq.NullTime{Time:time.Time{}, Valid:false}})
	result = append(result, &Forum{Id:25, Title:"Aanbiedingen en Kortingscodes", Description:".", Order:1, Forum_group_id:4, Post_count:0, Topic_count:0, Last_post_on:pq.NullTime{Time:time.Time{}, Valid:false}})
	return result    
}

func main() {

	// to make it repeatable
	defer os.RemoveAll("test.bleve")

	var index bleve.Index
	index = createForumgroupIndex("test.bleve")
	badForumGroup := &Forumgroup{
		Id:                4,
		Name:              "Algemene duurzame onderwerpen",
		Forum_category_id: 4,
		Ordering:          1,
		ForumCategory:     nil,
		Forums:            nil,
	}
	badForumGroup.Forums = MakeBadForums()
	err := indexForumgroups(index, []*Forumgroup{badForumGroup})
	if err != nil {
		log.Fatal(err)
	}

	searchPageData := &SearchPageData{
		Phrase: "en",
		Terms:  []string{"en"},
	}
	matches, err := searchInIndex(index, searchPageData)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Matches: %v", matches)
}
```

**Comment by blackreign** [comment] 2015-07-22 14:39
As a separate issue with either bleve or martini. When I use a multisearch the bug crashes the server, where in a normal search martini just displays an error page with the stack trace.

**Comment by mschoch** [comment] 2015-07-22 14:46
Cool, I'm able to reproduce it here now.  Can you open a separate issue and include the panic from the multisearch.

**Comment by mschoch** [comment] 2015-07-22 15:07
OK, it turns out this is another duplicate of https://github.com/blevesearch/bleve/issues/170

We have a pull-request which partially addresses the issue, but for now using highlighting with arrays of value is still problematic.

**Comment by blackreign** [comment] 2015-07-25 16:30
Aight, thanks for checking.

**Comment by mschoch** [comment] 2015-07-26 14:42
I know these bugs have been open for a while, but we are actively working on this.  We now have a plan forward, much of the code is already written I just have to finish the remaining portion.  Hopefully, you'll see progress next week.

**Comment by mschoch** [comment] 2015-07-31 18:46
I've just pushed a fix for this issue and retried your code.  It now shows:

```
1 matches, showing 1 through 1, took 406.429µs
    1. 4 (0.094697)
	Forums.Title
		Werk <mark>en</mark> Inkom<mark>en</mark>
```

Please reopen if you continue to have problems.

**Closed by mschoch** 2015-07-31 18:46 UTC
Labels: bug, duplicate

**Comment by blackreign** [comment] 2015-07-31 19:00
Works like a charm!
