### ISSUE TITLE
Close of closed channel in mergerLoop

### ISSUE THREAD

**Issue by remLse** [blevesearch/bleve#1609] opened 2021-07-22 15:31 UTC
Hello there.
The tests for my code sometimes fail due to something I believe to be a bug in bleve. It's non-deterministic, I get the bug about 10% of the times I run my tests. I was using v2.0.1 and upgraded to v2.0.6, which did not help. Here is the error message:
```
panic: close of closed channel

goroutine 453216 [running]:
github.com/blevesearch/bleve/v2/index/scorch.(*closeChWrapper).close(0xc000320c00)
	/home/cbc/go/pkg/mod/github.com/blevesearch/bleve/v2@v2.0.6/index/scorch/merge.go:228 +0x9b
github.com/blevesearch/bleve/v2/index/scorch.(*Scorch).planMergeAtSnapshot(0xc00005b400, 0xde4e10, 0xc0001a6010, 0xc0000a0000, 0xc00027a500, 0x0, 0x0)
	/home/cbc/go/pkg/mod/github.com/blevesearch/bleve/v2@v2.0.6/index/scorch/merge.go:405 +0x208a
github.com/blevesearch/bleve/v2/index/scorch.(*Scorch).mergerLoop(0xc00005b400)
	/home/cbc/go/pkg/mod/github.com/blevesearch/bleve/v2@v2.0.6/index/scorch/merge.go:68 +0x8b7
created by github.com/blevesearch/bleve/v2/index/scorch.(*Scorch).Open
	/home/cbc/go/pkg/mod/github.com/blevesearch/bleve/v2@v2.0.6/index/scorch/scorch.go:186 +0x168
```
Here are a few leads I gathered:
- The relevant channel is created at bleve/v2/index/scorch.go:272.
- The channel is passed to `s.segPlugin.Merge()` in the same file on line 322. If the defaultSegmentPlugin is used (which is the case for me), this close channel is passed to zapx/v15/merge.go:39 and passed along a few functions from there, but zapx does not seem to close the channel itself. So I don't think the bug is there.
- `closeChWrapper.close()` and `closeChWrapper.listen()` are each called exactly once, namely on lines 273 and 275.

Here's my guess of what's happening: The call to `cw.listen()`, which is running in a separate goroutine, receives a message from either `w.ch1` or `w.ctx.Done()` and proceeds to call `w.close()`. At about the same time, the function planMergeAtSnapshot executes and returns at line 405, causing the deferred statement `cw.close()` to execute. Now there are two goroutines executing `w.close()` on the same closeChWrapper. Both check if there is a message to be received from `w.closeCh`. The checks fail, because the channel hasn't been closed yet. Both goroutines proceed to the default case which attempts to close the channel, one of those two attemps fail and cause a run-time panic.

What do you think? I'm not terribly experienced with channels, so I'd love to know if my guess makes sense or not.

**Comment by mschoch** [comment] 2021-07-22 16:12
@sreekanth-cb this seems related to, or touching the same lines as the force-merge code you implemented.  Can you review this?

**Comment by sreekanth-cb** [comment] 2021-07-23 04:56
@remLse, your analysis makes sense to me.

The issue mostly happens due to the concurrent close attempt on the `close(w.closeCh)`  from two places as you identified. One from scorch's closeCh closure triggered from https://github.com/blevesearch/bleve/blob/e7235bec9cf6d984a1683372673d4f0571fa7d94/index/scorch/merge.go#L235
and the other from the `planMergeAtSnapshot` w.close() attempt here:
https://github.com/blevesearch/bleve/blob/e7235bec9cf6d984a1683372673d4f0571fa7d94/index/scorch/merge.go#L273

I am not yet able to reproduce this in a unit test and my understanding is that the chances for that would be rare, 
but one potential fix here would be to serialize the access in (w *closeChWrapper) close().

```
type closeChWrapper struct {
	m       sync.Mutex
	ch1     chan struct{}
	ctx     context.Context
	closeCh chan struct{}
}

func (w *closeChWrapper) close() {
	w.m.Lock()
	select {
	case <-w.closeCh:
	default:
		close(w.closeCh)
	}
	w.m.Unlock()
}
```

@mschoch, any thoughts/suggestions?

**Comment by mschoch** [comment] 2021-08-06 17:57
Also, I just noticed that I had logged this earlier, having seen failures on Windows CI runs: https://github.com/blevesearch/bleve/issues/1600

I will close that one now as a duplicate of this.

**Closed** 2021-08-09 15:28 UTC
