### ISSUE TITLE
Finding corruption in index

### ISSUE THREAD

**Issue by bcampbell** [blevesearch/bleve#263] opened 2015-10-28 07:13 UTC
Sorry in advance for the fuzziness of this - I've spent all day trying to pin it down to a nice little test data set, without luck. Will keep at it tomorrow, but wanted to see if anyone had any ideas.

Within the last week or so I've started to see corruption in my bleve indexes. I'm loading about 4000 newspaper articles into an index using goleveldb as the backend. I first noticed results missing from queries that should have picked them up. Then I noticed that some of the docIDs I was getting back weren't ones I'd loaded.

Here's my document type (there were loads of other fields, but I've stripped them out and the problem remains. I left Headline in because it was the easiest to use to spot the missing results).

```
type bleveArt struct {
	Headline string `json:"headline"`
}
```

My setup/mapping has been stripped down to:

```
	bleve.Config.DefaultKVStore = goleveldb.Name
	indexMapping := bleve.NewIndexMapping()

	artMapping := bleve.NewDocumentMapping()

	// english text - stemming, remove stopwords etc...
	textFld := bleve.NewTextFieldMapping()
	textFld.Analyzer = "en"
	textFld.Store = false

	artMapping.AddFieldMappingsAt("headline", textFld)

	indexMapping.DefaultType = "article"
	indexMapping.AddDocumentMapping("article", artMapping)
```

and my indexing:

```
func load(idx *bleve.Index, srcArts ...*Article) error {
	batch := idx.NewBatch()
	for _, src := range srcArts {
		artID := strconv.Itoa(src.ID)
		art := bleveArt{
			Headline: src.Headline,
		}
		batch.Index(artID, art)
	}
	return idx.Batch(batch)
}
```

(Note that my DocID is always an integer, converted into a string for bleve).

However, using `bleve_dump`, I can see that some of the docIDs and terms look very odd indeed:

```
$ bleve_dump -index articles.bleve -docID 156
Term: `blas` Field: 0 DocId: `�15` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 12 Start: 76 End 83 ArrayPositions: []uint64(nil)]
Key:   74 00 00 62 6c 61 73 ff ff 31 35                                                                    
Value: 01 ba 9a cf f4 03 00 0c 4c 53 00                                                                    

Term: `blast` Field: 0 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 3 Start: 13 End 19 ArrayPositions: []uint64(nil)]
Key:   74 00 00 62 6c 61 73 74 ff 31 35 36                                                                 
Value: 01 ba 9a cf f4 03 00 03 0d 13 00                                                                    

Term: `f�15` Field: 0 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 15 Start: 93 End 97 ArrayPositions: []uint64(nil)]
Key:   74 00 00 66 ff 31 35 ff 31 35 36                                                                    
Value: 01 ba 9a cf f4 03 00 0f 5d 61 00                                                                    

Term: `f` Field: 0 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 7 Start: 45 End 46 ArrayPositions: []uint64(nil)]
Key:   74 00 00 66 ff 31 35 36                                                                             
Value: 01 ba 9a cf f4 03 00 07 2d 2e 00                                                                    

Term: `holly` Field: 0 DocId: `ood` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 1 Start: 0 End 5 ArrayPositions: []uint64(nil)]
Key:   74 00 00 68 6f 6c 6c 79 ff 6f 6f 64                                                                 
Value: 01 ba 9a cf f4 03 00 01 00 05 00                                                                    

Term: `hollywood` Field: 0 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 4 Start: 20 End 33 ArrayPositions: []uint64(nil)]
Key:   74 00 00 68 6f 6c 6c 79 77 6f 6f 64 ff 31 35 36                                                     
Value: 01 ba 9a cf f4 03 00 04 14 21 00                                                                    

Term: `rather` Field: 0 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 2 Start: 6 End 12 ArrayPositions: []uint64(nil)]
Key:   74 00 00 72 61 74 68 65 72 ff 31 35 36                                                              
Value: 01 ba 9a cf f4 03 00 02 06 0c 00                                                                    

Term: `rather` Field: 0 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 19 Start: 113 End 119 ArrayPositions: []uint64(nil)]
Key:   74 00 00 72 61 74 68 65 72 ff 31 35 36                                                              
Value: 01 ba 9a cf f4 03 00 13 71 77 00                                                                    

Term: `tale` Field: 0 DocId: `t�1` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 18 Start: 108 End 112 ArrayPositions: []uint64(nil)]
Key:   74 00 00 74 61 6c 65 ff 74 ff 31                                                                    
Value: 01 ba 9a cf f4 03 00 12 6c 70 00                                                                    

Term: `talent` Field: 0 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 21 Start: 125 End 133 ArrayPositions: []uint64(nil)]
Key:   74 00 00 74 61 6c 65 6e 74 ff 31 35 36                                                              
Value: 01 ba 9a cf f4 03 00 15 7d 85 01 00                                                                 

Term: `women�156` Field: 0 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 9 Start: 56 End 65 ArrayPositions: []uint64(nil)]
Key:   74 00 00 77 6f 6d 65 6e ff 31 35 36 ff 31 35 36                                                     
Value: 01 ba 9a cf f4 03 00 09 38 41 00                                                                    

Term: `women` Field: 0 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 11 Start: 69 End 74 ArrayPositions: []uint64(nil)]
Key:   74 00 00 77 6f 6d 65 6e ff 31 35 36                                                                 
Value: 01 ba 9a cf f4 03 00 0b 45 4a 00                                                                    

Term: `blas` Field: 1 DocId: `�15` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 12 Start: 76 End 83 ArrayPositions: []uint64(nil)]
Key:   74 01 00 62 6c 61 73 ff ff 31 35                                                                    
Value: 01 ba 9a cf f4 03 00 0c 4c 53 00                                                                    

Term: `blast` Field: 1 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 3 Start: 13 End 19 ArrayPositions: []uint64(nil)]
Key:   74 01 00 62 6c 61 73 74 ff 31 35 36                                                                 
Value: 01 ba 9a cf f4 03 00 03 0d 13 00                                                                    

Term: `f�15` Field: 1 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 15 Start: 93 End 97 ArrayPositions: []uint64(nil)]
Key:   74 01 00 66 ff 31 35 ff 31 35 36                                                                    
Value: 01 ba 9a cf f4 03 00 0f 5d 61 00                                                                    

Term: `f` Field: 1 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 7 Start: 45 End 46 ArrayPositions: []uint64(nil)]
Key:   74 01 00 66 ff 31 35 36                                                                             
Value: 01 ba 9a cf f4 03 00 07 2d 2e 00                                                                    

Term: `holly` Field: 1 DocId: `ood` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 1 Start: 0 End 5 ArrayPositions: []uint64(nil)]
Key:   74 01 00 68 6f 6c 6c 79 ff 6f 6f 64                                                                 
Value: 01 ba 9a cf f4 03 00 01 00 05 00                                                                    

Term: `hollywood` Field: 1 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 4 Start: 20 End 33 ArrayPositions: []uint64(nil)]
Key:   74 01 00 68 6f 6c 6c 79 77 6f 6f 64 ff 31 35 36                                                     
Value: 01 ba 9a cf f4 03 00 04 14 21 00                                                                    

Term: `rather` Field: 1 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 2 Start: 6 End 12 ArrayPositions: []uint64(nil)]
Key:   74 01 00 72 61 74 68 65 72 ff 31 35 36                                                              
Value: 01 ba 9a cf f4 03 00 02 06 0c 00                                                                    

Term: `rather` Field: 1 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 19 Start: 113 End 119 ArrayPositions: []uint64(nil)]
Key:   74 01 00 72 61 74 68 65 72 ff 31 35 36                                                              
Value: 01 ba 9a cf f4 03 00 13 71 77 00                                                                    

Term: `tale` Field: 1 DocId: `t�1` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 18 Start: 108 End 112 ArrayPositions: []uint64(nil)]
Key:   74 01 00 74 61 6c 65 ff 74 ff 31                                                                    
Value: 01 ba 9a cf f4 03 00 12 6c 70 00                                                                    

Term: `talent` Field: 1 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 21 Start: 125 End 133 ArrayPositions: []uint64(nil)]
Key:   74 01 00 74 61 6c 65 6e 74 ff 31 35 36                                                              
Value: 01 ba 9a cf f4 03 00 15 7d 85 01 00                                                                 

Term: `women�156` Field: 1 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 9 Start: 56 End 65 ArrayPositions: []uint64(nil)]
Key:   74 01 00 77 6f 6d 65 6e ff 31 35 36 ff 31 35 36                                                     
Value: 01 ba 9a cf f4 03 00 09 38 41 00                                                                    

Term: `women` Field: 1 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 11 Start: 69 End 74 ArrayPositions: []uint64(nil)]
Key:   74 01 00 77 6f 6d 65 6e ff 31 35 36                                                                 
Value: 01 ba 9a cf f4 03 00 0b 45 4a 00                                                                    

```
(field 0 is headline, field 1 is _all)

That particular article has the headline:

"Helen Mirren blasts Hollywood’s 'Would you f*** her?' treatment of women, arguing they are cast for being sexy rather than talented".

Thanks, daily mail :- )

You can see from the dump, there's a lot not right. For a start, 'helen' is not there as a term.

As much as experience tells me that the bug is in _my_ code... I just can't figure out what I've done wrong. And the symptoms feel like some nasty memory-overwritting bug somewhere. And in Go, I'm inclined to think that implies some sort of tricky race condition...

Any ideas?

**Comment by bcampbell** [comment] 2015-10-28 07:21
Ahh! Writing all that prompted me to try out another backend - I dropped goleveldb DefaultKVStore setup, reran my program and ended up with a boltdb index which seems just fine:

```
$ bleve_dump -index articles.bleve -docID 156
Term: `argu` Field: 0 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 12 Start: 76 End 83 ArrayPositions: []uint64(nil)]
Key:   74 00 00 61 72 67 75 ff 31 35 36                                                                    
Value: 01 ba 9a cf f4 03 00 0c 4c 53 00                                                                    

Term: `blast` Field: 0 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 3 Start: 13 End 19 ArrayPositions: []uint64(nil)]
Key:   74 00 00 62 6c 61 73 74 ff 31 35 36                                                                 
Value: 01 ba 9a cf f4 03 00 03 0d 13 00                                                                    

Term: `cast` Field: 0 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 15 Start: 93 End 97 ArrayPositions: []uint64(nil)]
Key:   74 00 00 63 61 73 74 ff 31 35 36                                                                    
Value: 01 ba 9a cf f4 03 00 0f 5d 61 00                                                                    

Term: `f` Field: 0 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 7 Start: 45 End 46 ArrayPositions: []uint64(nil)]
Key:   74 00 00 66 ff 31 35 36                                                                             
Value: 01 ba 9a cf f4 03 00 07 2d 2e 00                                                                    

Term: `helen` Field: 0 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 1 Start: 0 End 5 ArrayPositions: []uint64(nil)]
Key:   74 00 00 68 65 6c 65 6e ff 31 35 36                                                                 
Value: 01 ba 9a cf f4 03 00 01 00 05 00                                                                    

Term: `hollywood` Field: 0 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 4 Start: 20 End 33 ArrayPositions: []uint64(nil)]
Key:   74 00 00 68 6f 6c 6c 79 77 6f 6f 64 ff 31 35 36                                                     
Value: 01 ba 9a cf f4 03 00 04 14 21 00                                                                    

Term: `mirren` Field: 0 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 2 Start: 6 End 12 ArrayPositions: []uint64(nil)]
Key:   74 00 00 6d 69 72 72 65 6e ff 31 35 36                                                              
Value: 01 ba 9a cf f4 03 00 02 06 0c 00                                                                    

Term: `rather` Field: 0 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 19 Start: 113 End 119 ArrayPositions: []uint64(nil)]
Key:   74 00 00 72 61 74 68 65 72 ff 31 35 36                                                              
Value: 01 ba 9a cf f4 03 00 13 71 77 00                                                                    

Term: `sexi` Field: 0 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 18 Start: 108 End 112 ArrayPositions: []uint64(nil)]
Key:   74 00 00 73 65 78 69 ff 31 35 36                                                                    
Value: 01 ba 9a cf f4 03 00 12 6c 70 00                                                                    

Term: `talent` Field: 0 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 21 Start: 125 End 133 ArrayPositions: []uint64(nil)]
Key:   74 00 00 74 61 6c 65 6e 74 ff 31 35 36                                                              
Value: 01 ba 9a cf f4 03 00 15 7d 85 01 00                                                                 

Term: `treatment` Field: 0 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 9 Start: 56 End 65 ArrayPositions: []uint64(nil)]
Key:   74 00 00 74 72 65 61 74 6d 65 6e 74 ff 31 35 36                                                     
Value: 01 ba 9a cf f4 03 00 09 38 41 00                                                                    

Term: `women` Field: 0 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 11 Start: 69 End 74 ArrayPositions: []uint64(nil)]
Key:   74 00 00 77 6f 6d 65 6e ff 31 35 36                                                                 
Value: 01 ba 9a cf f4 03 00 0b 45 4a 00                                                                    

Term: `argu` Field: 1 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 12 Start: 76 End 83 ArrayPositions: []uint64(nil)]
Key:   74 01 00 61 72 67 75 ff 31 35 36                                                                    
Value: 01 ba 9a cf f4 03 00 0c 4c 53 00                                                                    

Term: `blast` Field: 1 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 3 Start: 13 End 19 ArrayPositions: []uint64(nil)]
Key:   74 01 00 62 6c 61 73 74 ff 31 35 36                                                                 
Value: 01 ba 9a cf f4 03 00 03 0d 13 00                                                                    

Term: `cast` Field: 1 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 15 Start: 93 End 97 ArrayPositions: []uint64(nil)]
Key:   74 01 00 63 61 73 74 ff 31 35 36                                                                    
Value: 01 ba 9a cf f4 03 00 0f 5d 61 00                                                                    

Term: `f` Field: 1 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 7 Start: 45 End 46 ArrayPositions: []uint64(nil)]
Key:   74 01 00 66 ff 31 35 36                                                                             
Value: 01 ba 9a cf f4 03 00 07 2d 2e 00                                                                    

Term: `helen` Field: 1 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 1 Start: 0 End 5 ArrayPositions: []uint64(nil)]
Key:   74 01 00 68 65 6c 65 6e ff 31 35 36                                                                 
Value: 01 ba 9a cf f4 03 00 01 00 05 00                                                                    

Term: `hollywood` Field: 1 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 4 Start: 20 End 33 ArrayPositions: []uint64(nil)]
Key:   74 01 00 68 6f 6c 6c 79 77 6f 6f 64 ff 31 35 36                                                     
Value: 01 ba 9a cf f4 03 00 04 14 21 00                                                                    

Term: `mirren` Field: 1 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 2 Start: 6 End 12 ArrayPositions: []uint64(nil)]
Key:   74 01 00 6d 69 72 72 65 6e ff 31 35 36                                                              
Value: 01 ba 9a cf f4 03 00 02 06 0c 00                                                                    

Term: `rather` Field: 1 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 19 Start: 113 End 119 ArrayPositions: []uint64(nil)]
Key:   74 01 00 72 61 74 68 65 72 ff 31 35 36                                                              
Value: 01 ba 9a cf f4 03 00 13 71 77 00                                                                    

Term: `sexi` Field: 1 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 18 Start: 108 End 112 ArrayPositions: []uint64(nil)]
Key:   74 01 00 73 65 78 69 ff 31 35 36                                                                    
Value: 01 ba 9a cf f4 03 00 12 6c 70 00                                                                    

Term: `talent` Field: 1 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 21 Start: 125 End 133 ArrayPositions: []uint64(nil)]
Key:   74 01 00 74 61 6c 65 6e 74 ff 31 35 36                                                              
Value: 01 ba 9a cf f4 03 00 15 7d 85 01 00                                                                 

Term: `treatment` Field: 1 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 9 Start: 56 End 65 ArrayPositions: []uint64(nil)]
Key:   74 01 00 74 72 65 61 74 6d 65 6e 74 ff 31 35 36                                                     
Value: 01 ba 9a cf f4 03 00 09 38 41 00                                                                    

Term: `women` Field: 1 DocId: `156` Frequency: 1 Norm: 0.288675 Vectors: [Field: 0 Pos: 11 Start: 69 End 74 ArrayPositions: []uint64(nil)]
Key:   74 01 00 77 6f 6d 65 6e ff 31 35 36                                                                 
Value: 01 ba 9a cf f4 03 00 0b 45 4a 00                                                                    

```

**Comment by mschoch** [comment] 2015-10-28 13:42
Yeah, this is bad.  I'll definitely take a look today.

**Comment by mschoch** [comment] 2015-10-28 15:44
My initial attempts to reproduce this have failed.  But, we recently made changes to the code such that we're highly dependent on the KVStores honoring their contract for when they copy bytes and when they hold references to them.  It seems likely the bug is related to this.

Can you get the git has of the following repos:

github.com/blevesearch/bleve
github.com/syndtr/goleveldb

Meanwhile I'll start looking at any recent goleveldb changes in this areas.

**Comment by mschoch** [comment] 2015-10-28 15:53
Actually I take that back I am able to reproduce the problem.  It has all the signs of goleveldb not actually honoring the contract it claims.

The docs here: https://github.com/syndtr/goleveldb/blob/master/leveldb/batch.go#L94-L98 say `It is safe to modify the contents of the argument after Put returns` but the fact that the entry where 'helen' should be is actually 'holly' wither a later row for 'hollywood' sure looks like our reuse of the buffer was not safe as the docs claimed, but actually a problem.

I'll quick change the code to make another copy to that behavior is safe again, then followup with the goleveldb team regarding this discrepency.

**Comment by mschoch** [comment] 2015-10-28 15:56
Hmmn, quick fix didn't work.  Perhaps things are getting corrupted on the way out not the way in.  Still looking.

**Comment by mschoch** [comment] 2015-10-28 16:02
OK, output from the `leveldbutil dump` utility seems to confirm this.  The data in index looks correct, but we're getting corrupted reading it back out.  Still working on a fix.

**Comment by mschoch** [comment] 2015-10-28 16:08
OK, I pushed one fix related to this issue, it only concerns the dump command though.  https://github.com/blevesearch/bleve/commit/d1b07f4909f89de7c1a9af6d07dcf80927c7d89a

Can you provide a search that doesn't work that you expect to work?  I tried searching for 'helen' which was not visible in the dump output before, but this search correctly found the result.  So, I'm not yet sure if the same problem affects search.

**Comment by mschoch** [comment] 2015-10-28 16:12
Ah yeah there are problems there too:

https://github.com/blevesearch/bleve/blob/master/index/upside_down/reader.go#L68-L73

We don't copy the key/value because we copy the pieces of it that we need, but we call Next() before those copies happen, so the data can already be overwritten.

**Comment by mschoch** [comment] 2015-10-28 16:25
OK, I've pushed another fix for this.  

https://github.com/blevesearch/bleve/commit/2bd3ef4080d7c3988987cdf31f1c433710cbab92

We now copy relevant sections of the k/v pairs before advancing the iterator.  I don't have a clean test case to reproduce this yet, so if you're able to test this and report back that would be great.

I'll try to improve the testing situation for this after lunch.

**Comment by bcampbell** [comment] 2015-10-28 17:17
I just pulled the changes you made and initial observations are good - I haven't seen the problem yet. So fingers crossed!

**Comment by mschoch** [comment] 2015-11-23 14:03
I'm going to close this, please open a new issue if you see problems again.

**Closed by mschoch** 2015-11-23 14:03 UTC

**Comment by xomaczar** [comment] 2016-07-12 18:35
@mschoch  I just
1. go get -u github.com/blevesearch/bleve
2. using bleave_create, bleve_index & bleve_dump to create bleave index
3. When I bleve_dump that index I see lots of terms that make no sense.
                                                                          
```

Term: `L0
         ` Field: 1 DocId: `1` Frequency: 1 Norm: 0.049029 Vectors: []
Key:   74 01 00 4c 30 0b 10 ff 31                                                                          
Value: 01 ab a5 a3 ea 03                                                                                   

Term: `L0
         ` Field: 1 DocId: `1` Frequency: 3 Norm: 0.049029 Vectors: []
Key:   74 01 00 4c 30 0b 14 ff 31                                                                          
Value: 03 ab a5 a3 ea 03     
```

**Comment by mschoch** [comment] 2016-07-12 20:38
Do your documents contain number?  The encoded terms for numbers often look weird in the index and result in many unprintable characters.

Can you share the document/mapping you're using, or post the full bleve_dump somewhere?  Probably the mapping/data file and bleve_ commands you used would be sufficient.

**Comment by xomaczar** [comment] 2016-07-12 21:44
@mschoch thanks a lot for your quick response I think I figured out what's the different between the older api and the latest one. If I try to index a document as a slice of bytes (marshalled json) instead of the string my index contains weird data and I'm on unable to search. Indexing the string document seems to fix the problem
