### ISSUE TITLE
panic in highlight fragmenter

### ISSUE THREAD

**Issue by dtynn** [blevesearch/bleve#202] opened 2015-05-14 06:39 UTC
this is my code 
https://gist.github.com/dtynn/17ce8d32b9284bebbd7e
and this is the panic info
https://gist.github.com/dtynn/7d7fd0003ec6c43ce952

https://github.com/blevesearch/bleve/blob/master/search/highlight/fragmenters/simple/fragmenter_simple.go#L39
it seems that the method here should check the orig's length?

**Comment by dtynn** [comment] 2015-05-14 06:58
https://gist.github.com/dtynn/8be6ed079fa6df8f0270
well , the code get the result 

2015/05/14 14:48:27 result: 123: 1 matches, showing 1 through 1, took 340.655µs
    1. highlight (0.137229)
	Tags
		<span class="highlight">abc</span>

which is obviously incorrect.

maybe it should do something more to make sure the docField is the right one.
https://github.com/blevesearch/bleve/blob/master/search/highlight/highlighters/simple/highlighter_simple.go#L81

**Comment by mschoch** [comment] 2015-05-14 11:47
Thanks, I believe this is a duplicate of #170

**Comment by mschoch** [comment] 2015-07-31 18:45
I just pushed a fix for this issue and retried your example code.  I now get:

```
2015/07/31 14:40:53 result: 123: 1 matches, showing 1 through 1, took 102.987µs
    1. highlight (0.137229)
	Tags
		<mark>123</mark> 45 678
```

Please reopen it if you continue to observe the problem.

**Closed by mschoch** 2015-07-31 18:45 UTC
Labels: bug, duplicate

**Comment by dtynn** [comment] 2015-08-01 00:45
thanks marty, it seems good
