### ISSUE TITLE
speedup index open without counting docs from scratch each time

### ISSUE THREAD

**Issue by darren** [blevesearch/bleve#573] opened 2017-04-04 17:37 UTC
currently it takes some time counting docs when opening the index.
if the index grows bigger, opening the index will be slower.
We have a bleve index stored in boltdb with file size  100GB, the db file is located on a SSD disk
it takes 9 minutes to open the index before bleve can serve search request.

**Comment by mschoch** [comment] 2017-04-05 17:17
It looks like we'll have to use the merge operator to implement this functionality.  If we just used a set operation with the new value of the doc count, we'd have to hold a lock across the whole batch.  KV stores that don't have a native merge operator will still end up using a lock, but its a bit more fine-grained.

**Comment by japettyjohn** [comment] 2017-07-03 22:53
Could the count be stored in the meta file or the database itself and read from there on startup?

**Comment by mschoch** [comment] 2017-07-03 23:01
Yes, it can be stored in the database.  The challenge is updating it.  Every batch we execute has to also update the value of the count.  If we implement it using a SET operation in the underlying KV store then we have to first GET the previous value, and add to it, all of which while holding  a lock so that no other operations can happen at the same time and disrupt the values.

The alternative is to use the MERGE operation, which bleve can either use natively, or emulate on top of KV stores which don't support it.  The problem is that you can only have one merge function per KV store, and we already have one that works differently (for merging term dictionary rows).  This is a deal breaker, we can make the merge operator more complicated, to first look at the key, and behave differently based on it.  But, it means its not just like a 5-line change.

A simpler solution, which might help some use cases would be to simply allow the document count to be wrong at first, and count the rows asynchronously.  Its a bit more complicated than that since we have to keep the new count, and combine it with the old count once its ready.

We acknowledge this is a problem (which is why the bug is still open), but since neither solution is trivial, and it hasn't been high priority for us, it has remain unfixed so far.

**Comment by japettyjohn** [comment] 2017-07-03 23:15
Ya, none of those are trivial - totally understood.

Not sure if this would solve the scenario @Darren is encountering, but I could conceivably use read-only where the open time is critical to my application. Given the increasing size of my indexes I'd prefer doing the re-index offline anyways.

I think with read-only in place, a simple caching approach could be viable.

**Comment by japettyjohn** [comment] 2017-07-03 23:41
From my cursory look, the docCount is used once given as part in making the IndexReader, which in turns exposes it with DocCount() - which I think is only used by DocCountHandler and NewMatchAllSearcher (within bleve proper).

Instead of making the assumption on read-only this could be an explicit open option.

**Comment by japettyjohn** [comment] 2017-07-06 23:12
I went ahead and did the configuration approach. Tell me what you think https://github.com/japettyjohn/bleve/commit/2d5193afd69f3e2702f7fb9300595c566d6fe5e2

**Comment by slavikm** [comment] 2018-02-19 08:12
@mschoch any progress here? We're encountering very slow index open times (which randomly take much longer on occasion). Would using Moss help here? Any update on Moss in general?

**Comment by mschoch** [comment] 2018-02-19 15:02
No progress, it's not directly a pain point for us right now, so we're not actively working on this.  Moss won't really help here as it is the upsidedown index scheme that its above all the k/v stores that relies on this approach of counting the docs upon opening the index.

General moss update is that we're not working it any more.  We believe we've taken the pluggable key/value store approach in bleve as fas as it can (or as far as we can take it anyway).  Instead we've started on a new index scheme named 'scorch'.  It writes segments directly to disk and does not use a key/value store for storing the index data (it does use boltdb, but just for snapshot data, not index data, so perf isn't really an issue).  This new index scheme produces files that are often 50% the size of the previous index (depending on what you compare it to).  This new index scheme also does not have this slow opening problem because index segments are immutable and record how many documents are present in the segment metadata.  So, we're hard at working making scorch production ready (it is available on the master branch already, but is still in development).

**Comment by steveyen** [comment] 2018-12-10 20:57
it's been awhile on this one, where the center of gravity of enhancements and work has indeed moved onwards to the "scorch" indexing engine -- so, gonna mark this closed as highly likely we'll won't fix -- steve

**Closed by steveyen** 2018-12-10 20:57 UTC

**Comment by lunny** [comment] 2019-01-13 15:16
Also encountered this issue with about 400G index boltdb file. Is scorch production ready?

**Comment by lunny** [comment] 2019-01-14 02:04
Will try it, thanks!
