### ISSUE TITLE
possible major scorch indexing performance regression

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#1037] opened 2018-10-31 14:00 UTC
Using the beer-search application, I used all the defaults, and built the index:
```
$ ./beer-search 
2018/10/31 15:41:59 GOMAXPROCS: 8
2018/10/31 15:41:59 Creating new index...
2018/10/31 15:41:59 Listening on :8094
2018/10/31 15:41:59 Indexing...
2018/10/31 15:42:00 Indexed 1000 documents, in 1.04s (average 1.04ms/doc)
2018/10/31 15:42:01 Indexed 2000 documents, in 2.00s (average 1.00ms/doc)
2018/10/31 15:42:02 Indexed 3000 documents, in 3.05s (average 1.02ms/doc)
2018/10/31 15:42:03 Indexed 4000 documents, in 4.15s (average 1.04ms/doc)
2018/10/31 15:42:05 Indexed 5000 documents, in 5.45s (average 1.09ms/doc)
2018/10/31 15:42:06 Indexed 6000 documents, in 6.73s (average 1.12ms/doc)
2018/10/31 15:42:07 Indexed 7000 documents, in 8.10s (average 1.16ms/doc)
2018/10/31 15:42:08 Indexed 7303 documents, in 8.53s (average 1.17ms/doc)
```

Next I confirmed this was using upsidedown/boltdb:

```
$ ls -l beer-search.bleve/      
total 196728
-rw-r--r-- 1 mschoch mschoch        47 Oct 31 15:55 index_meta.json
-rw------- 1 mschoch mschoch 211177472 Oct 31 15:56 store
```

Then I modified the code to force using scorch, deleted the previously built index, and reran it.

```
beerIndex, err = bleve.NewUsing(*indexPath, indexMapping, "scorch", "scorch", nil)
```
and

```
$ rm -rf beer-search.bleve 
$ go build
```

```
$ ./beer-search 
2018/10/31 15:43:43 GOMAXPROCS: 8
2018/10/31 15:43:43 Creating new index...
2018/10/31 15:43:45 Listening on :8094
2018/10/31 15:43:45 Indexing...
2018/10/31 15:43:50 Indexed 1000 documents, in 4.63s (average 4.63ms/doc)
2018/10/31 15:43:51 Indexed 2000 documents, in 5.98s (average 2.99ms/doc)
2018/10/31 15:44:02 Indexed 3000 documents, in 16.96s (average 5.65ms/doc)
2018/10/31 15:44:09 Indexed 4000 documents, in 23.86s (average 5.97ms/doc)
2018/10/31 15:44:19 Indexed 5000 documents, in 34.38s (average 6.88ms/doc)
2018/10/31 15:44:30 Indexed 6000 documents, in 45.17s (average 7.53ms/doc)
2018/10/31 15:44:43 Indexed 7000 documents, in 57.76s (average 8.25ms/doc)
2018/10/31 15:44:49 Indexed 7303 documents, in 64.24s (average 8.80ms/doc)
```

Then to confirm that it was infact using scorch:

```
$ ls -l beer-search.bleve/store
total 16556
-rw------- 1 mschoch mschoch 15859387 Oct 31 15:44 000000000074.zap
-rw------- 1 mschoch mschoch   877168 Oct 31 15:44 000000000079.zap
-rw------- 1 mschoch mschoch   262144 Oct 31 15:44 root.bolt
```

The last time I tried this, scorch was considerably faster.

**Comment by mschoch** [comment] 2018-10-31 14:04
This was quite a while ago obviously, but recall that I once observed:

![beer-search-perf](https://user-images.githubusercontent.com/298143/47793286-a1ed9d80-dd26-11e8-9809-2798d414c82c.png)

**Comment by mschoch** [comment] 2018-10-31 14:16
Here are the results of the git bisect (good cases are all < 5s and bad cases almost a minute or more)

```
84502bf2c73fd9a85477d7018220e0af6a69374e is the first bad commit
commit 84502bf2c73fd9a85477d7018220e0af6a69374e
Author: Sreekanth Sivasankaran <sreekanth.sivasankaran@couchbase.com>
Date:   Wed Jul 11 14:40:35 2018 +0530

    MB-29923 - high memory consumption in scorch
    
    The fix aims to loosen the persister-merger lock
    stepping and also introduces a configurable
    wait in the persister work loop to favour healthier
    in-memory segment merges.

:040000 040000 205a998b3bb4e5b596990d01c59d5f920015fda8 3e752d5ccdc082d8cc39d2dc78ebd6477c3a9cad M	index
:040000 040000 11e4e0868e9a30b9e0c67cbb4bbeea598d1a389c eddc46a0a0dfec2e3848fb4b130e2aa211690e2e M	test
```

**Comment by mschoch** [comment] 2018-10-31 14:27
One theory is that this behavior may only be observed when using safe batches (default) and not observed with the unsafe batch mode (used by Couchbase FTS).

**Comment by mschoch** [comment] 2018-10-31 14:34
We experimented changing/disabling these config settings:

```
diff --git a/index/scorch/persister.go b/index/scorch/persister.go
index 01102c2f..f179be48 100644
--- a/index/scorch/persister.go
+++ b/index/scorch/persister.go
@@ -36,9 +36,9 @@ import (
 
 var DefaultChunkFactor uint32 = 1024
 
-var DefaultPersisterNapTimeMSec int = 2000 // ms
+var DefaultPersisterNapTimeMSec int = 0 // ms
 
-var DefaultPersisterNapUnderNumFiles int = 1000
+var DefaultPersisterNapUnderNumFiles int = 0
 
 type persisterOptions struct {
        // PersisterNapTimeMSec controls the wait/delay injected into
```

And this seems to have resolved the apparent problem (with unknown impact to memory usage of the program).

```
2018/10/31 16:31:59 GOMAXPROCS: 8
2018/10/31 16:31:59 Creating new index...
2018/10/31 16:31:59 Listening on :8094
2018/10/31 16:31:59 Indexing...
2018/10/31 16:32:00 Indexed 1000 documents, in 0.59s (average 0.59ms/doc)
2018/10/31 16:32:01 Indexed 2000 documents, in 1.06s (average 0.53ms/doc)
2018/10/31 16:32:01 Indexed 3000 documents, in 1.58s (average 0.53ms/doc)
2018/10/31 16:32:02 Indexed 4000 documents, in 2.07s (average 0.52ms/doc)
2018/10/31 16:32:02 Indexed 5000 documents, in 2.62s (average 0.52ms/doc)
2018/10/31 16:32:03 Indexed 6000 documents, in 3.12s (average 0.52ms/doc)
2018/10/31 16:32:03 Indexed 7000 documents, in 3.67s (average 0.52ms/doc)
2018/10/31 16:32:03 Indexed 7303 documents, in 3.87s (average 0.53ms/doc)
```

**Comment by abhinavdangeti** [comment] 2018-10-31 17:39
@mschoch You're very right. My tests did reveal the regression with couchbase FTS (index build time ~50s) when unsafe_batch isn't set (use default setting), but with the option set to true, the index build time is less than 3s.
 
Ping @sreekanth-cb, we need to take a closer look at how the persister nap settings cause this regression when unsafe_batch:false.

**Comment by mschoch** [comment] 2018-10-31 21:47
Agreed, this works OK for the beer-search use case, but in the larger real-world case they ran out of memory.  They will attempt to experiment with other values, but there are some open questions still about how we can get good default behavior.  Regular users of bleve will want perf to be no worse than upsidedown when using safe batches, and would not expect to run out of memory.

**Comment by sreekanth-cb** [comment] 2018-11-01 05:34
Thanks @mschoch for finding this regression, Yes. In case we wait for persistence of batches(safe batches) then the above commit will cause the slow down of overall indexing. 
I shall analyse a bit further, quick thinking is that - nap defaults could be reset at bleve level and cbft could override it accordingly.  Else totally skipping napping with safe batches are another option too.

**Comment by guydemi** [comment] 2018-11-01 14:15
**Crashed**
* PersisterNapTimeMSec=250 & PersisterNapUnderNumFiles=250, crashed due to OOM
* PersisterNapTimeMSec=500 & PersisterNapUnderNumFiles=250, crashed due to OOM
* PersisterNapTimeMSec=750 & PersisterNapUnderNumFiles=400, crashed due to OOM

**Default Finished**
* PersisterNapTimeMSec=2000 & PersisterNapUnderNumFiles=1000 (same as default values), duration 50m, memory 92%, size 4.0G - barely passed, ~1% memory usage from OOM

**Finished**
* PersisterNapTimeMSec=1000 & PersisterNapUnderNumFiles=500, duration 30m15, size 6.1G
* PersisterNapTimeMSec=0 & PersisterNapUnderNumFiles=1000, duration 25m19, memory 91%, size 6.2G

**Unstable**
* PersisterNapTimeMSec=500 & PersisterNapUnderNumFiles=0, duration 16m24, memory 93% - it finished once but failed the 2nd try

*For reference, using Bleve (without scorch), memory usage peaks at 75%*

**Comment by guydemi** [comment] 2018-11-01 14:16
Hey guys, some testing of the sleep values on our data:

On a 16GB machine,
**Crashed**
* PersisterNapTimeMSec=250 & PersisterNapUnderNumFiles=250, crashed due to OOM
* PersisterNapTimeMSec=500 & PersisterNapUnderNumFiles=250, crashed due to OOM
* PersisterNapTimeMSec=750 & PersisterNapUnderNumFiles=400, crashed due to OOM

**Default Finished**
* PersisterNapTimeMSec=2000 & PersisterNapUnderNumFiles=1000 (same as default values), duration 50m, memory 92%, size 4.0G - barely passed, ~1% memory usage from OOM

**Finished**
* PersisterNapTimeMSec=1000 & PersisterNapUnderNumFiles=500, duration 30m15, size 6.1G
* PersisterNapTimeMSec=0 & PersisterNapUnderNumFiles=1000, duration 25m19, memory 91%, size 6.2G

**Unstable**
* PersisterNapTimeMSec=500 & PersisterNapUnderNumFiles=0, duration 16m24, memory 93% - it finished once but crashed the 2nd try

*For reference, using Bleve (without scorch), memory usage peaks at 75%*

**Comment by aviadl** [comment] 2018-11-03 18:57
All run with default - which is safe ...

**Comment by sreekanth-cb** [comment] 2018-11-05 12:11
@mschoch , I am yet to find an explicit safe batch handling logic for upside down index. 
Not sure whether we are silently ignoring the safe batch requests with upsidedown/moss.

@aviadl, Can you confirm in the above experiments, 

1. Were you trying to execute Safe batches concurrently from many threads?
2. What was the rough average batch size?

Yet to figure out the connection between high memory usage with Safe batches in scorch in a non concurrent mode.

**Comment by guydemi** [comment] 2018-11-05 15:33
@sreekanth-cb, 1-2(max) concurrent write at a time with batches of 100

**Comment by sreekanth-cb** [comment] 2018-11-05 17:20
I think, two potential problems with safe batch approach are,

1. With high density data, it may result in too many segment files on disk , causing a file handle spike 
    issue in background.
2. Too many segment files could result in high memory pressure due to heavy file segment 
     merging/compactions happening in background.

**Comment by mschoch** [comment] 2018-11-06 04:05
Hey @sreekanth-cb 

I've been (and still am) travelling, so I haven't kept close touch with this issue, but wanted to drop a few thing in here.  Safe batches is the default behavior for Bleve.  The reason is that most users cannot use unsafe batches (Couchbase and a handful of others are the exception here).  The expectation for most users is that when Index() or Batch() returns that there data has been persisted to disk.

With upside_down, there was nothing coded explicilty for it because it relies on key/value stores.  Key value stores are most typically used for primary data storage, which assumes a user wants durability.  So you wont find anything explicit about that.

At a high level scorch was intended to be a replacement for upside_down.  But, if it performs worse than upside_down in the default configuration of safe batches, or if it crashes with OOM without a way for users to avoid it, then no one will accept scorch as a replacement.  That is the bottom line.

**Comment by sreekanth-cb** [comment] 2018-11-08 05:33
Thanks @mschoch for the quick response, though for some reason I missed this reply. 
Yep, I was pondering/checking with the team on what were the motivations behind the default safe batch configuration.  Now it is clear.

Earlier I ended up concluding that, we opted for a slower `running out of file handles` issue than an easier/quicker OOM issue for this choice. :)

**Comment by sreekanth-cb** [comment] 2018-11-09 09:49
Hi @guydemi , I have made the defaults like PersisterNapTimeMSec=0 & PersisterNapUnderNumFiles=1000 with some comments to help further tweaking for the users depending on their conditions. 

With this fix, the original issue reported by @mschoch with beer-search is fixed.

**Comment by sreekanth-cb** [comment] 2018-11-14 11:19
Closing this ticket as the original issue reported is fixed.

**Closed by sreekanth-cb** 2018-11-14 11:19 UTC
