### ISSUE TITLE
There is no way to convert a search result data into a JSON/struct

### ISSUE THREAD

**Issue by dorsha** [blevesearch/bleve#252] opened 2015-10-15 06:14 UTC
I think this feature can be really useful (similar to how elastic works).

For example, in elastic this can be done to convert result into struct easily:

```
someStruct = &someStruct{}
err = json.Unmarshal(*searchResult.Source, someStruct)
```

**Comment by albertog** [comment] 2015-10-15 16:06
+1

**Comment by mschoch** [comment] 2017-05-17 13:03
I believe this is a duplicate of https://github.com/blevesearch/bleve/issues/174

**Closed by mschoch** 2017-05-17 13:03 UTC
Labels: enhancement
