### ISSUE TITLE
scorch panics on arm (raspberry pi)

### ISSUE THREAD

**Issue by darren** [blevesearch/bleve#1231] opened 2019-05-31 15:34 UTC
## uname -a
`
Linux raspberrypi 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux
`

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x12724]

goroutine 1 [running]:
github.com/blevesearch/bleve/index/scorch.(*Scorch).openBolt(0x2af8000, 0xe0f1b8, 0x2af8000)
        /Users/darren/Sources/go/pkg/mod/github.com/blevesearch/bleve@v0.7.1-0.20190510153952-e0de6a8c9c5f/index/scorch/scorch.go:218 +0x12c
github.com/blevesearch/bleve/index/scorch.(*Scorch).Open(0x2af8000, 0x6, 0x280ac80)
        /Users/darren/Sources/go/pkg/mod/github.com/blevesearch/bleve@v0.7.1-0.20190510153952-e0de6a8c9c5f/index/scorch/scorch.go:160 +0x1c
github.com/blevesearch/bleve.openIndexUsing(0x28285a0, 0xb, 0x0, 0x2aba7d0, 0x0, 0x0)
        /Users/darren/Sources/go/pkg/mod/github.com/blevesearch/bleve@v0.7.1-0.20190510153952-e0de6a8c9c5f/index_impl.go:173 +0x434
github.com/blevesearch/bleve.Open(...)
        /Users/darren/Sources/go/pkg/mod/github.com/blevesearch/bleve@v0.7.1-0.20190510153952-e0de6a8c9c5f/index.go:286
```

Due to  https://github.com/golang/go/issues/599

**Comment by mschoch** [comment] 2019-05-31 15:46
The line causing the problem is:

https://github.com/blevesearch/bleve/blob/e0de6a8c9c5f4ca9b84159124ec1a385d740d79a/index/scorch/scorch.go#L218

And the field being accessed is here:

https://github.com/blevesearch/bleve/blob/e0de6a8c9c5f4ca9b84159124ec1a385d740d79a/index/scorch/stats.go#L98

However, all fields in the struct are 64-bits, so I don't see how it could be misaligned.  I guess the problem is that the entire stats struct is misaligned within the scorch struct. (first field is bool, which ruins everything)

**Comment by darren** [comment] 2019-05-31 16:09
Hi mschoch,

Thanks for your great work on scorch, we have used scorch in our products and amazed at its performance.
Though raspberry pi is not our target environment, I just want to make it at home, :)

Anyway,  the misalignment appears in  struct `Scorch` instead of in stats struct:

```go
type Scorch struct {
	nextSegmentID uint64
	nextSnapshotEpoch    uint64
	stats         Stats
	iStats internalStats
...
}
```  

and another one I encountered:

``` go
type cachedDocs struct {
	size  uint64
	m     sync.Mutex                  // As the cache is asynchronously prepared, need a lock
	cache map[string]*cachedFieldDocs // Keyed by field
}

```

**Comment by mschoch** [comment] 2019-06-03 01:43
Is there a reason you closed this? It appears to be a valid issue.

**Comment by tmm1** [comment] 2019-07-23 19:01
Looks like @darren worked around this in https://github.com/darren/bleve/commit/99bcef21a044bf98f1f8ab07042bf4b25236f210

Unfortunately this class of bug is really hard to detect at compile time, and easy to regress when adding field members.

One workaround is to use pointers for fields requiring atomic access, i.e.`*uint64` so a new piece of aligned memory is allocated for the value.

There is some work happening upstream to teach `go vet` to detect these issues, but it is not very comprehensive at the moment. See https://github.com/golang/go/issues/11891

**Comment by tmm1** [comment] 2019-07-24 22:10
@mschoch Do you have any thoughts here? Are you okay reshuffling some fields to fix the immediate alignment issue?

**Comment by mschoch** [comment] 2019-07-24 22:17
Yeah we're happy to shuffle the fields, it is an easy fix, and one we've applied before.  But as you pointed out in a previous comment, the problem is it is easy to accidentally re-introduce them.

**Closed** 2019-07-29 16:54 UTC
