### ISSUE TITLE
How to use 'moss' store with cmd/bleve?

### ISSUE THREAD

**Issue by insmo** [blevesearch/bleve#529] opened 2017-02-09 10:08 UTC
The following works:
```
> ./bleve create -s boltdb boltdb.data
> ./bleve index boltdb.data/ -j ../../test/tests/basic/data/a.json
Indexing: a
> ./bleve query boltdb.data/ marty
1 matches, showing 1 through 1, took 205.996µs
    1. a (0.068614)
	name
		marty
 ```

However, replacing boltdb with moss yields an error.
```
> ./bleve create -s moss moss.data
> ./bleve index moss.data/ -j ../../test/tests/basic/data/a.json
Error: error opening bleve index: error parsing mapping JSON: unexpected end of JSON input
mapping contents:

Usage:
  bleve index [index path] [data paths ...] [flags]

Flags:
  -j, --json      Parse the contents as JSON, defaults true. (default true)
  -d, --keepDir   Keep the directory in the dodcument id, defaults false.
  -x, --keepExt   Keep the extension in the document id, defaults false.

error opening bleve index: error parsing mapping JSON: unexpected end of JSON input
mapping contents:
 ```

The moss store meta file did persist fine, though.

```
> cat moss.data/index_meta.json 
{"storage":"moss","index_type":"upside_down"}
```

**Comment by mschoch** [comment] 2017-02-09 12:36
The problem is that "moss" by default doesn't actually persist data.  The "bleve create" command is supposed to create the actual "store" file (you see this after the boltdb create, but not after the moss one).  This initial empty store should contain the mapping.  And, it is this mapping that can't be found on the subsequent command, is what the error message is complaining about.

In my opinion, this is part of the larger usability issues for moss.  I'm going to assign it to @steveyen to propose how we can improve this.

**Comment by simonz05** [comment] 2017-02-09 12:48
Thanks for the quick follow up.

I found this issue when I tried to compare `moss` to `boltdb` in my own application. I wasn't able to figure out how to persist `moss` index, while it worked with the other storage engines. I might as well ask the question here; is it possible to persist a `moss`-backed bleve index as things stand today, or does that require additional work on the `moss` storage implementation in bleve?

**Comment by mschoch** [comment] 2017-02-09 13:54
Yes, it does support storage, but it's not enabled by default.  To enable you need to pass the kv config option that you see here:

https://github.com/blevesearch/bleve-bench/blob/master/configs/moss-store.json#L6

Unfortunately, the command-line tools don't offer a way to include any kv config options.

In my opinion, what we need to clean up is the "moss" adapter in bleve.  The defaults are unreasonable, and somewhat dangerous.   For example, when the index tier calls New() on moss, and the config includes a value for "path", it still defaults to memory-only behavior.  In this case it should enable storage.  Second, it default to using as much ram as possible, which just isn't a very safe default.

But, these are straightforward to clean up, we just need to prioritize it.

**Comment by bt** [comment] 2017-06-06 12:31
Hey @mschoch, has there been any updates to this? I just starting using Bleve and I figured that `moss` would be the fastest driver available and now I'm running into issues where creating a new store without indexing anything, then reading it back will give an error similar to the OP:

```
error parsing mapping JSON: unexpected end of JSON input
mapping contents:
```

Upon looking at the internals of Bleve, I can see this is being triggered at https://github.com/blevesearch/bleve/blob/master/index_impl.go#L195 which seems to be caused by the fact that the `moss` mapping is not written into the store yet.

Any idea how much effort this will take to make it work? Or, any pointers on what I should do to help this move forward?

**Comment by mschoch** [comment] 2017-06-06 13:50
Pinging @steveyen 

Can we discuss making the change so that in bleve when you choose "moss" it defaults to moss+mossStore.  The ability moss as an alternate mem-only option is also interesting, but lower priority.

If we do that part first, then moss becomes usable for people out of the box.

Second priority, we have to document how it can be used safely.  As moss persists asynchronously, there are some additional requirements which must be observed to not lose data.

**Comment by bt** [comment] 2017-06-07 04:07
So, by just changing the `mossLowerLevelStoreName` to `mossStore` doesn't seem to work giving the same error as above, because it doesn't seem to write the `_mapping` key into the store yet.

I'm not too familiar with the internals of Bleve, but I'm guessing that the lower store hasn't triggered a write yet?

**Comment by bt** [comment] 2017-06-07 14:46
Yes, so that's pretty much what I worked out after a few hours of debugging the inner workings of both Bleve and `moss`. Basically this is because `moss` has a goroutine that's responsible to update the lower level store and that takes a while to trigger the loop.

Would `moss` be considering changes to help support use-cases like Bleve?

I also noticed another race condition related issue which I'm not 100% sure if it's worth fixing but basically upon calling `Close()` on an index, it doesn't close the lower level store, so there is a chance that the `.moss` file doesn't even get created. If you'd like to have a look, I can make a PR for it.

**Comment by mschoch** [comment] 2017-06-07 15:54
Moss already works quite well with bleve, we have customers running it in production.  But, it just doesn't do so right out of the box.  You have to configure and use it in a particular way.

It would be nice if moss supported durable persistence (optionally) on a per-batch basis.  We would like to add support for that, but it's not trivial.  I'd suggest you maybe add your comments/thoughts/ideas to this moss issue: https://github.com/couchbase/moss/issues/17

Regarding the potential race, yes if you see issue in the bleve+moss integration please file bug or send PR.

**Comment by bt** [comment] 2017-06-07 23:28
Oh crap, lol I think the total confusion from me was that I saw `moss` as just a faster, more superior kvstore compared to an in-memory kvstore. That's probably why I'm having an impression that persistence is a must. However, given this is not the case, I agree this is a better discussion for the issue linked compared to an issue with Bleve.

However, with the current implementation, the Bleve runtime will similarly need some sort of a `sleep for 30 seconds` to get the persistence goroutine to kick in otherwise it won't write to disk.

I noticed that @steveyen mentions a specific line in the linked issue, mainly: `hooking up an event callback as seen in various unit tests`. I'll have a look into this and see how it can fit into the `create` command for Bleve.

**Comment by mschoch** [comment] 2017-06-08 00:48
Moss is not just an in-memory story, it does persist the data to disk, it just does so asynchronously.

There are a variety of different use cases for bleve, and as-is moss is only suitable for some of them.  In our case, the index is secondary, and we have a resumable stream of data from the primary source.  So, while we do want the data persisted, we don't ever care if it crashes/fails, because we can always restart and just pick up where we left off.  Not everyone has this use case though, which is why Bleve adopted a more conservative approach of presuming that all operations were durably persisted by the time they return.

Bleve will never have any `sleep for 30 seconds` because that doesn't really guarantee correct behavior.  Instead there are 2 options:

1) introduce durable persistence to moss, and default to that behavior (this makes all bleve operations safe and work as expected)  advanced users that have a use case that can take advantage of it could toggle a flag and disable durable persistence.

2) moss could offer a new version of CloseEx() which guarantees that by the time it returns all data has been drained to disk.  this would let the application see the expected behavior if they can guarantee waiting for a safe shutdown, but it still doesn't help if your app crashes.

None of this should be wired up to the `bleve create` command, as that is just one specific place the problem is observed.  It affects every single API call in bleve when using moss.

What I'd recommend right now is evaluate whether or not your application can be designed to remember which data has been indexed, and resume after crash.  If so, you may be able to use moss.  If not, you should not continue to pursue moss, as until other enhancements come, you'll just continue to observe problems.

**Comment by ptimson** [comment] 2019-11-25 18:00
Any updates on this?

**Comment by mschoch** [comment] 2019-11-25 18:03
@ptimson No.  As far as I know, no one is working on moss any longer, and we do not recommend it for any use case.

**Closed** 2020-04-24 12:45 UTC
Labels: bug
