### ISSUE TITLE
Geo Queries Example

### ISSUE THREAD

**Issue by jaakidup** [blevesearch/bleve#836] opened 2018-03-16 20:04 UTC
I'm really liking Bleve, the text searching is working exactly for what I need.
Now, I understand that Geo queries are new in the project and not yet documented, but I would appreciate a simple example of how to query documents, based on a text search on field "name", but sorted according to "geo" distance,

for example data
{
 "name": "Jacques"
 "geo": {
    lat: -33.00
    lon: 18.00
 }
}

This is the only thing holding me back at the moment from choosing Bleve over Elasticsearch.

Thanks

**Comment by mschoch** [comment] 2018-03-16 20:18
I don't think we have any Go code that demonstrates this, but there is an integration test for it.  The only difference is that they are described using JSON.  Here is the relevant "sort by geo distance portion":

https://github.com/blevesearch/bleve/blob/master/test/tests/geo/searches.json#L15-L25

In the Go version you'll want to start by setting the  SortByCustom method (the simplified string syntax  used by the base SortBy method isn't expressive enough for geo sort).  You pass to this method a search.SortOrder which is just a slice of search.SearchSort objects.  SearchSort is an interface, and the SortGeoDistance satsifies the interface.   So you'll want to call NewSortGeoDistance() with the values you want to use.  Roughly something like this (pseudo-code not tested):

```
req := NewSearchRequest(... your existing search)

lon, lat := the location you want to compute distance form for sort purposes (maybe users current loc)
sortGeo, err := NewSortGeoDistance("geoFieldInDoc", "mi", lon, lat, desc)
if err != nil {
...
}

req.SortByCustom(search.SortOrder{sortGeo})

res, err := index.Search(req)
```

Hopefully this gets you started, let me know if you have more questions.

**Comment by jaakidup** [comment] 2018-03-18 18:03
Thanks Marty, that was a great help.
I thought I'd post what worked for me in case someone else is interested.
First is a query that is sorts results according to geo position.
`	lon, lat := 18.8283052, -33.9413322 // sort from this geo point

	query := bleve.NewMatchQuery("Search for this")
	searchRequest := bleve.NewSearchRequest(query)

	sortGeo, _ := search.NewSortGeoDistance("location", "km", lon, lat, true)

	searchRequest.SortByCustom(search.SortOrder{sortGeo})
	searchResults, _ := index.Search(searchRequest)`

And then, here is a query that searches for text and only returns results that are within the distance specified.
`	lon, lat := 18.8283052, -33.9413322

	textQuery := bleve.NewMatchQuery("Art Fashion")
	distanceQuery := bleve.NewGeoDistanceQuery(lon, lat, "100km")
	distanceQuery.SetField("location")

	conRequest := bleve.NewConjunctionQuery()
	conRequest.AddQuery(textQuery)
	conRequest.AddQuery(distanceQuery)

	searchRequest := bleve.NewSearchRequest(conRequest)
	searchResults, _ := index.Search(searchRequest)
`

**Comment by hubyhuby** [comment] 2018-05-06 15:44
Dear @jaakidup 
I have sent my "products struct" to bleve and it works well for text search.
Also I haven t done any tweaking and just set in advance Long and lat as followed in my struct.
I see that you use a "location" that seems made of the two...
Please let me know how I can make it to work ;)


WHat I have : 
...
        City          nulls.String `json:"city" db:"city"`
	Country       nulls.String `json:"country" db:"country"`
	Long          float64      `json:"long" db:"long"`
	Lat           float64      `json:"lat" db:"lat"`
	Userid        uuid.UUID    `json:"userid" db:"userid"`
...
WHAT is in the tests : 
"location": {
            "lon": -122.107799,
            "lat": 37.399285
}
Lat           float64      `json:"lat" db:"lat"`

**Comment by jaakidup** [comment] 2018-05-07 11:09
I chose to use a "location" slice/array, so just before putting the struct in bleve, I create the location slice.

```
	Latitude         float64   `json:"latitude"`
	Longitude        float64   `json:"longitude"`
	Location         []float64 `json:"location"` // Built up using Latitude and Longitude
```
```

func (p *Product) forSaving() *Product {
	p.Location = []float64{p.Longitude, p.Latitude} // This is what you're asking
	return p
}


```
Hope this helps.

**Comment by hubyhuby** [comment] 2018-05-07 14:09
Thanks a lot @jaakidup ,
I will give it a try, that s cool I can do it afterward ;)
Also do I have to rebuild my index....or can I just ad my upcoming data with the updated product location ?
Thanks for your help

**Comment by mschoch** [comment] 2018-08-06 13:58
@hubyhuby updating data should work fine.  You only need to rebuild the index if you want to make structural changes to the index (like new fields, or changing field mappings)

**Comment by mschoch** [comment] 2018-08-06 13:58
Closing this, as it seems like everyone has it working now.  If not, please re-open or open a new issue.

**Closed by mschoch** 2018-08-06 13:58 UTC

**Comment by hubyhuby** [comment] 2019-04-20 07:34
Dear @mschoch ,
I am trying to implement a geo search based on the beer-search example.
For now I am getting no results, I guess I need to do the mapping for the "geo" field before beeing able to request it . (in the demo mapping.go geo is not set)
Also I cannot find a doc or code sample for  geo mapping :
I have tried things like : 
	//Geo mapping
	locationMapping := bleve.NewGeoPointFieldMapping()
	//locationMapping.Analyzer= ???
	beerMapping.AddFieldMappingsAt("geo", locationMapping)

The doc for mapping: https://blevesearch.com/docs/Index-Mapping/

Example JSON :
{"name":"Bob","city":"Lyon","state":"Rhone","code":"","country":"France","phone":"000000","website":"http://site.com","type":"agence","updated":"2010-07-22 20:00:20","description":"","address":["Hoogstraat 2A"],"geo":{"lat":50.7668,"lon":4.3081}}

**Comment by hubyhuby** [comment] 2019-04-21 07:02
Dear @jaakidup ,
As several persons seems to be strugling with geo on bleve, I have put up a sample demo project.
I cannot make the geo work either.
Could you give me your advices on how to make it work there : 
https://github.com/hubyhuby/bleve-search-example/blob/b885560792dd8c902a8716213e0b198d36b16220/main.go#L113

**Comment by mschoch** [comment] 2019-04-22 23:22
@hubyhuby I reviewed your program, and I think the problem is that you add your geo mapping to the "beer" type like this:

```
beerMapping.AddFieldMappingsAt("geo", locationMapping)
```

That's fine, except that in the data set, there are 2 types, `beer` and `brewery`.  And unfortunately, only breweries have data for the "geo" field.

So I made the following change to your application.  In the mapping.go file, add or change the geo mapping to be like this:

```
breweryMapping.AddFieldMappingsAt("geo", locationMapping)
```

Then it should work (make sure you delete the old index).

I get the following results:

```
Search for records around a geo point:

 1289 matches, showing 1 through 10, took 52.664956ms
    1. australian_brewing_corporation (1.069924)
    2. brasserie_de_tahiti (1.069924)
    3. carlton_and_united_breweries (1.069924)
    4. cervecera_jerome (1.069924)
    5. cervejaria_kaiser_brasil (1.069924)
    6. cervejaria_sudbrack (1.069924)
    7. coopers_brewery (1.069924)
    8. dux_de_lux (1.069924)
    9. emerson_brewing (1.069924)
   10. epic_brewing_company (1.069924)
```

**Comment by hubyhuby** [comment] 2019-05-04 15:54
Hi @mschoch ,
Thanks a lot for this help. It now works like a charm.
I have updated my example app.
Thanks for this great FTS project !

**Comment by hubyhuby** [comment] 2019-06-23 06:59
A litlle hint for those who are trying to use geo sort with bleve.
"search" referes to the import lib ;) In my code I had a variable called "search". Which some of you might have too. So you must import "github.com/blevesearch/bleve/search" and NOT use a variable called "search" in your code.

	"github.com/blevesearch/bleve/search"

 lon, lat := 18.8283052, -33.9413322 
	query := bleve.NewMatchQuery("Search for this")
	searchRequest := bleve.NewSearchRequest(query)

	sortGeo, _ := search.NewSortGeoDistance("location", "km", lon, lat, true)

	searchRequest.SortByCustom(search.SortOrder{sortGeo})
	searchResults, _ := index.Search(searchRequest)
